### ISSUE TITLE
FOR THE LAST FUCKING TIME

### ISSUE THREAD

**Issue by HausemasterIssue** [teejwrld/teejs-oyvey#1]
STOP MAKING OYVEY SKIDS, FOR FIVE SECONDS!

**Comment by noatmc** [comment]
> STOP MAKING OYVEY SKIDS, FOR FIVE SECONDS!

fuck, that's too hard

**Comment by master7720** [comment]
> STOP MAKING OYVEY SKIDS, FOR FIVE SECONDS!

xD fr

**Comment by teejwrld** [comment]
> STOP MAKING OYVEY SKIDS, FOR FIVE SECONDS!

no
